### ISSUE TITLE
Different color .hex code after .isLight call

### ISSUE THREAD

**Issue by HoraceSupertramp** [Aletheios/nanocolor#1]
Two different calls to the .hex property of any nanocolor instance returns two different hex codes if those calls are interleaved by a isLight call.

`const color = nanocolor('#ffff00'); // yellow`
`console.log(color.hex);                 // correctly outputs '#ffff00'`
`console.log(color.isLight);            // correctly outputs 'true'`
`console.log(color.hex);                 // outputs '#e2e2e2';`

The wrong color that is provided after a isLight call seems to be always a shade of gray.

**Comment by Aletheios** [comment]
@HoraceSupertramp Thanks for reporting this issue. Fixed in version 1.0.2.
