### ISSUE TITLE
Not working on IE <= 11

### ISSUE THREAD

**Issue by HoraceSupertramp** [Aletheios/nanocolor#2]
the rgb2hex() method within transforms.js won't work on IE11 and lower just because of the String.prototype.padStart call at line 76. That's such a pity. Maybe replace that call with something that could extend browser support to IE?

**Comment by Aletheios** [comment]
Thanks for the hint. `padStart` wasn't the only JS feature that IE didn't support. I've rewritten those lines now so they're compatible with IE 11. I don't want to add polyfills because they'd significantly increase the file size of the library.

New version is published as 1.1.0.

**Comment by HoraceSupertramp** [comment]
Thank you very much for your work and for your timely support. Good job!
